/**
 * SMTP Email Notifier
 * Sends alerts via direct Gmail SMTP instead of paid providers like SendGrid.
 */

import nodemailer from 'nodemailer';
import { logger } from '../../../utils/logger';

export class EmailNotifier {
  private transporter;
  private limitReachedUntil: number = 0;

  constructor() {
    this.transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS // Requires 'App Password' for Gmail
      }
    });
  }

  async sendAlert(to: string, subject: string, body: string) {
    // Check if we are in a cooldown period due to rate limiting
    if (Date.now() < this.limitReachedUntil) {
      logger.warn('SMTP Email skipped: Gmail daily limit previously exceeded. Resuming after cooldown.');
      return;
    }

    try {
      const info = await this.transporter.sendMail({
        from: `"ShadowScan Pro" <${process.env.SMTP_USER}>`,
        to,
        subject,
        text: body,
        html: `<div style="background:#0a0e1a; color:#e8eaf6; padding:20px; font-family:sans-serif;">
                <h2 style="color:#ff3366;">🚨 ShadowScan Alert</h2>
                <p>${body}</p>
                <hr style="border-color:#1e2d4f;"/>
                <small>Generated by ShadowScan Pro — Automated Threat Intelligence</small>
              </div>`
      });
      
      logger.info(`Alert Email Sent: ${info.messageId}`);
    } catch (error: any) {
      if (error.responseCode === 550 && error.response.includes('Daily user sending limit exceeded')) {
        logger.error('CRITICAL: Gmail Daily Sending Limit Exceeded. No more emails can be sent for today.');
        // Set cooldown for 12 hours to avoid spamming the log with this specific error
        this.limitReachedUntil = Date.now() + (12 * 60 * 60 * 1000);
      } else {
        logger.error('SMTP Email Failed:', error);
      }
    }
  }
}
